# os: [macos-latest, ubuntu-latest, windows-latest]

name: Release

# on:
#   push:
#     branches:
#       - main

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - name: Make
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run make
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          out/**/*Setup.exe
          out/**/*.dmg
          out/**/*.deb
          out/**/*.rpm
          out/**/*.zip
