# os: [macos-latest, ubuntu-latest, windows-latest]

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - name: publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
